language: python
os: linux
branches:
  only:
    - main
    - dev
matrix:
  python: - "3.10"
  python: - "3.11"
  python: - "3.12"
jobs:
  install: 
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python blog/manage.py test
