language: python
os: linux
branches:
  only:
    - main
    - dev
matrix:
  - python: "3.11.0"
  - python: "3.12.6"
jobs:
  install: 
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python blog/manage.py test
