# Generated by Django 4.2.1 on 2024-05-03 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanionDto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_ID', models.CharField(max_length=100)),
                ('skin_ID', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InfoDto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_datetime', models.BigIntegerField()),
                ('game_length', models.FloatField()),
                ('game_variation', models.CharField(max_length=100)),
                ('game_version', models.CharField(max_length=100)),
                ('tft_set_number', models.IntegerField()),
                ('queue_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemDto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('B.F. Sword', 'B F Sword'), ('Needlessly Large Rod', 'Needlessly Large Rod'), ('Recurve Bow', 'Recurve Bow'), ('Sparring Gloves', 'Sparring Gloves'), ('Tear of the Goddess', 'Tear Of The Goddess'), ('Chain Vest', 'Chain Vest'), ('Giant_s Belt', 'Giant S Belt'), ('Negatron Cloak', 'Negatron Cloak')], max_length=100)),
                ('num_units', models.IntegerField()),
                ('style', models.IntegerField()),
                ('tier', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SummonerDto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=100)),
                ('puuid', models.CharField(max_length=100)),
                ('summoner_id', models.CharField(max_length=100)),
                ('summonerLevel', models.IntegerField()),
                ('profileIconId', models.IntegerField()),
                ('revisionDate', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TraitDto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num_units', models.IntegerField()),
                ('style', models.IntegerField()),
                ('tier_current', models.IntegerField()),
                ('tier_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UnitDto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.CharField(max_length=100)),
                ('chosen', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('rarity', models.IntegerField()),
                ('tier', models.IntegerField()),
                ('items', models.ManyToManyField(to='summoners.itemdto')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantDto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_left', models.IntegerField()),
                ('last_round', models.IntegerField()),
                ('level', models.IntegerField()),
                ('placement', models.IntegerField()),
                ('players_eliminated', models.IntegerField()),
                ('puuid', models.CharField(max_length=100)),
                ('time_eliminated', models.FloatField()),
                ('total_damage_to_players', models.IntegerField()),
                ('companion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summoners.companiondto')),
                ('traits', models.ManyToManyField(to='summoners.traitdto')),
                ('units', models.ManyToManyField(to='summoners.unitdto')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataDto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_version', models.CharField(max_length=100)),
                ('match_id', models.CharField(max_length=100)),
                ('participants', models.ManyToManyField(to='summoners.participantdto')),
            ],
        ),
        migrations.CreateModel(
            name='MatchDto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summoners.infodto')),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summoners.metadatadto')),
            ],
        ),
        migrations.AddField(
            model_name='infodto',
            name='participants',
            field=models.ManyToManyField(to='summoners.participantdto'),
        ),
    ]
