# Generated by Django 4.2.1 on 2024-05-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatadto',
            name='participants',
            field=models.ManyToManyField(related_name='metadata', to='summoners.participantdto'),
        ),
    ]
