# Generated by Django 4.2.1 on 2024-07-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0002_alter_metadatadto_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='AugmentDto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='unitdto',
            name='chosen',
        ),
        migrations.AlterField(
            model_name='itemdto',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='participantdto',
            name='augments',
            field=models.ManyToManyField(to='summoners.augmentdto'),
        ),
    ]
