# Generated by Django 4.2.1 on 2024-07-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0003_augmentdto_remove_unitdto_chosen_alter_itemdto_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdto',
            name='name',
            field=models.CharField(choices=[('B.F. Sword', 'B F Sword'), ('Needlessly Large Rod', 'Needlessly Large Rod'), ('Recurve Bow', 'Recurve Bow'), ('Sparring Gloves', 'Sparring Gloves'), ('Tear of the Goddess', 'Tear Of The Goddess'), ('Chain Vest', 'Chain Vest'), ('Giant_s Belt', 'Giant S Belt'), ('Negatron Cloak', 'Negatron Cloak')], max_length=100),
        ),
    ]
