# Generated by Django 4.2.1 on 2024-07-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0004_alter_itemdto_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitdto',
            name='items',
        ),
        migrations.DeleteModel(
            name='ItemDto',
        ),
        migrations.AddField(
            model_name='unitdto',
            name='items',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
