# Generated by Django 4.2.1 on 2024-07-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0005_remove_unitdto_items_delete_itemdto_unitdto_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='companiondto',
            name='item_ID',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
