# Generated by Django 4.2.1 on 2024-07-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0006_companiondto_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='unitdto',
            name='items',
        ),
        migrations.AddField(
            model_name='unitdto',
            name='items',
            field=models.ManyToManyField(to='summoners.itemdto'),
        ),
    ]
